server.port=${PORT:8080}
spring.application.name=test-jdbi
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=liquibase/test/jdbi-changelog.xml
spring.liquibase.default-schema=store

app.security.api-key-header=X-Api-Token
app.security.api-key-token=
app.security.cors-domains=*.szclsb.ch
app.security.cors-methods=POST,PUT,PATCH,DELETE,OPTIONS