server.port=${PORT:8080}
spring.application.name=test-jdbi

app.security.api-key-header=X-Api-Token
app.security.api-key-token=
app.security.cors-domains=*.szclsb.ch
app.security.cors-methods=POST,PUT,PATCH,DELETE,OPTIONS